"""empty message

Revision ID: 39ad583850e7
Revises: 
Create Date: 2020-10-09 18:01:02.869518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ad583850e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('games', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('create_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('games'),
    sa.UniqueConstraint('id')
    )
    op.create_table('message_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('online_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=356), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_level', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_pass', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=54), nullable=True),
    sa.Column('pub_date', sa.String(), nullable=True),
    sa.Column('cate_id', sa.Integer(), nullable=True),
    sa.Column('post_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cate_id'], ['games.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('topic')
    )
    op.create_table('mesage_forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('message_user', sa.String(length=568), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('send_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['announcements.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post_raiting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_like', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['announcements.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_raiting')
    op.drop_table('mesage_forum')
    op.drop_table('announcements')
    op.drop_table('user')
    op.drop_table('online_users')
    op.drop_table('message_user')
    op.drop_table('games')
    # ### end Alembic commands ###
